/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Format } from '../../models/format';

export interface GetFormate$Params {
}

export function getFormate(http: HttpClient, rootUrl: string, params?: GetFormate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Format>>> {
  const rb = new RequestBuilder(rootUrl, getFormate.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Format>>;
    })
  );
}

getFormate.PATH = '/api/formate';
