/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AhbDiffSide } from '../models/ahb-diff-side';

/**
 * A line in the AHB diff comparison, containing data from both versions joined from v_ahbtabellen
 */
export interface AhbDiffLine {

  /**
   * The diff status from v_ahb_diff
   */
  diff_status: 'unchanged' | 'modified' | 'added' | 'deleted';

  /**
   * The id_path from v_ahb_diff used to join with v_ahbtabellen
   */
  id_path: string;

  /**
   * Data from v_ahbtabellen for the new (A) version
   */
  new?: AhbDiffSide;

  /**
   * Data from v_ahbtabellen for the old (B) version
   */
  old?: AhbDiffSide;

  /**
   * The sort_path for ordering
   */
  sort_path: string;
}
