/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * AHB line data from v_ahbtabellen for one side of the comparison
 */
export interface AhbDiffSide {
  bedingung?: string | null;
  data_element?: string | null;
  line_ahb_status?: string | null;
  line_name?: string | null;
  line_type?: string | null;
  qualifier?: string | null;
  segment_code?: string | null;
  segmentgroup_key?: string | null;
}
