/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AhbDiffStats } from '../models/ahb-diff-stats';

/**
 * Aggregated diff statistics per Pruefidentifikator
 */
export interface AhbDiffSummary {

  [key: string]: AhbDiffStats;
}
