/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AhbDiffLine } from '../models/ahb-diff-line';
export interface AhbDiff {
  lines: Array<AhbDiffLine>;
  meta: {
'pruefidentifikator': string;
'format_version_new': string;
'format_version_old': string;

/**
 * Description of the Pruefidentifikator in the new version
 */
'description_new'?: string | null;

/**
 * Description of the Pruefidentifikator in the old version
 */
'description_old'?: string | null;
};
}
