/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AhbDiffLine } from '../models/ahb-diff-line';
export interface AhbDiff {
  lines: Array<AhbDiffLine>;
  meta: {
'pruefidentifikator': string;
'format_version_a': string;
'format_version_b': string;

/**
 * Description of the Pruefidentifikator in version A (new)
 */
'description_a'?: string | null;

/**
 * Description of the Pruefidentifikator in version B (old)
 */
'description_b'?: string | null;
};
}
