/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Ahb {
  lines: Array<{
'ahb_expression': string;
'conditions'?: string;
'data_element': string;
'guid': string;
'index': number;
'name': string;
'section_name': string;
'segment_code': string;
'segment_group_key': string;
'value_pool_entry': string;

/**
 * EBD decision-tree key (e.g. E_0401) detected in value_pool_entry, if any
 */
'ebd_key'?: string | null;
'line_type': string;
}>;
  meta: {
'description': string;
'direction': string;
'pruefidentifikator': string;
'versionsnummer': string;
'veroeffentlichungsdatum': string;
};
}
