/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Latest publication date of the AHB data
 */
export interface Datenstand {

  /**
   * Publication date in DD.MM.YYYY format
   */
  veroeffentlichungsdatum: string;
}
