/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Standard error body produced by the global error handler
 */
export interface ErrorResponse {

  /**
   * Machine-readable error code
   */
  error: string;

  /**
   * Human-readable error message
   */
  message: string;
}
