/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One operator should be provided per field
 */
export interface FilterValue {
  contains?: string;
  endsWith?: string;
  eq?: string;
  in?: Array<string>;
  isNotNull?: boolean;
  isNull?: boolean;
  neq?: string;
  startsWith?: string;
}
