/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One operator should be provided per field. An empty filter object `{}` applies no constraint on that field.
 */
export interface FilterValue {
  /**
   * Case-insensitive substring match. Use `*` to match text between search segments; text before the first `*` must be at the start, while text after the final segment may follow (for example, `Änderung*TR`).
   */
  contains?: string;
  endsWith?: string;
  eq?: string;

  /**
   * Match any of the listed values (SQL `IN`). An **empty array is ignored** — it applies no constraint on this field and therefore matches all rows, rather than matching none. Omit the `in` operator (or the whole filter) when there is nothing to filter by.
   */
  in?: Array<string>;
  isNotNull?: boolean;
  isNull?: boolean;
  neq?: string;
  startsWith?: string;
}
