/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * An EDIFACT format version code (`FVYYYY`, e.g. `FV2510`), or an ISO date (`YYYY-MM-DD`) which is resolved server-side to the format version valid on that day.
 */
export type FormatVersion = string;
