/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Error returned when the health check secret is missing or invalid
 */
export interface HealthCheckError {
  error: string;
}
