/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HealthCheckResult } from '../models/health-check-result';

/**
 * Aggregated result of all individual health checks
 */
export interface HealthCheckResponse {
  checkResults: Array<HealthCheckResult>;

  /**
   * Unix timestamp (seconds) at which the health check finished
   */
  finishedAt: number;
}
