/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchFilters } from '../models/search-filters';
import { SortRule } from '../models/sort-rule';
export interface SearchQueryRequest {
  filters?: SearchFilters;
  page: number;

  /**
   * Maximum 200
   */
  pageSize: number;

  /**
   * Global case-insensitive search across the 11 listed fields
   */
  q: string;
  sort: Array<SortRule>;
}
