/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilterValue } from '../models/filter-value';
export interface SearchFilters {
  bedingung?: FilterValue;
  data_element?: FilterValue;
  description?: FilterValue;
  format?: FilterValue;
  format_version?: FilterValue;
  line_ahb_status?: FilterValue;
  line_name?: FilterValue;
  pruefidentifikator?: FilterValue;
  qualifier?: FilterValue;
  segment_code?: FilterValue;
  segmentgroup_key?: FilterValue;
}
