/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchItem {
  bedingung?: string;
  data_element?: string;
  description?: string;

  /**
   * inbound/outbound indicator
   */
  direction?: string;
  format: string;
  format_version: string;
  line_ahb_status?: string;
  line_name?: string;
  pruefidentifikator: string;
  qualifier?: string;
  segment_code?: string;
  segmentgroup_key?: string;
}
