/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchFilters } from '../models/search-filters';
import { SortRule } from '../models/sort-rule';
export interface SearchQueryRequest {
  filters?: SearchFilters;
  page: number;

  /**
   * Maximum 200
   */
  pageSize: number;

  /**
   * Global case-insensitive search across the 11 listed fields. Without `*` this is a substring match. A `*` makes the match prefix-anchored — the text before the first `*` must be at the start of the field, `*` matches any text between segments, and text after the final segment may follow (for example, `Änderung*TR` matches values that start with `Änderung` and contain `TR` afterwards).
   */
  q: string;
  sort: Array<SortRule>;
}
