/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SearchItem } from '../models/search-item';
export interface SearchQueryResponse {
  items?: Array<SearchItem>;
  page?: number;
  pageSize?: number;
  total?: number;
}
