services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        BUILD_DATE: dummy
        COMMIT_ID: wip
        VERSION: v0.0.0-local
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_7Z_ARCHIVE_PASSWORD=${DB_7Z_ARCHIVE_PASSWORD}
      - ENVIRONMENT=docker
    depends_on:
      - upload-documents
