/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AhbDiff } from '../../models/ahb-diff';
import { FormatVersion } from '../../models/format-version';

export interface GetAhbDiff$Params {

/**
 * Pruefidentifikator to compare
 */
  pruefi: string;

/**
 * First format version (typically newer)
 */
  'format-version-a': FormatVersion;

/**
 * Second format version (typically older)
 */
  'format-version-b': FormatVersion;
}

export function getAhbDiff(http: HttpClient, rootUrl: string, params: GetAhbDiff$Params, context?: HttpContext): Observable<StrictHttpResponse<AhbDiff>> {
  const rb = new RequestBuilder(rootUrl, getAhbDiff.PATH, 'get');
  if (params) {
    rb.path('pruefi', params.pruefi, {});
    rb.query('format-version-a', params['format-version-a'], {});
    rb.query('format-version-b', params['format-version-b'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AhbDiff>;
    })
  );
}

getAhbDiff.PATH = '/api/ahb-diff/{pruefi}';
