/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AhbDiffSummary } from '../../models/ahb-diff-summary';
import { FormatVersion } from '../../models/format-version';

export interface GetAhbDiffSummary$Params {

/**
 * The newer format version to compare
 */
  'format-version-new': FormatVersion;

/**
 * The older format version to compare
 */
  'format-version-old': FormatVersion;
}

export function getAhbDiffSummary(http: HttpClient, rootUrl: string, params: GetAhbDiffSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<AhbDiffSummary>> {
  const rb = new RequestBuilder(rootUrl, getAhbDiffSummary.PATH, 'get');
  if (params) {
    rb.query('format-version-new', params['format-version-new'], {});
    rb.query('format-version-old', params['format-version-old'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AhbDiffSummary>;
    })
  );
}

getAhbDiffSummary.PATH = '/api/ahb-diff-summary';
