/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AhbPruefiDiff } from '../../models/ahb-pruefi-diff';
import { FormatVersion } from '../../models/format-version';

export interface GetPruefiDiff$Params {

/**
 * First Pruefidentifikator to compare
 */
  pruefiOld: string;

/**
 * Second Pruefidentifikator to compare
 */
  pruefiNew: string;

/**
 * The format version both Pruefidentifikatoren are compared in (FVxxxx code, 'current', or an ISO date YYYY-MM-DD)
 */
  'format-version': FormatVersion;
}

export function getPruefiDiff(http: HttpClient, rootUrl: string, params: GetPruefiDiff$Params, context?: HttpContext): Observable<StrictHttpResponse<AhbPruefiDiff>> {
  const rb = new RequestBuilder(rootUrl, getPruefiDiff.PATH, 'get');
  if (params) {
    rb.path('pruefiOld', params.pruefiOld, {});
    rb.path('pruefiNew', params.pruefiNew, {});
    rb.query('format-version', params['format-version'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AhbPruefiDiff>;
    })
  );
}

getPruefiDiff.PATH = '/api/pruefi-diff/{pruefiOld}/{pruefiNew}';
