config:
  ahb-tabellen:appPath: app
  ahb-tabellen:appServicePlanSkuName: "B1"
  ahb-tabellen:appServicePlanSkuTier: "Basic"
  ahb-tabellen:bedingungsbaumBaseUrl: https://bedingungsbaum.hochfrequenz.de
  ahb-tabellen:containerPort: "80"
  ahb-tabellen:db_7z_archive_password:
    secure: AAABAG9VAmOftI7npdJm+AxiHDF90IWlsDdCQxNGeJImf4j21yqJi+GDTxI71zYlQ38da4IAEuzc/fXW1p4=
  ahb-tabellen:ebdBaseUrl: https://ebd.hochfrequenz.de
  ahb-tabellen:environment: production
  ahb-tabellen:ghcr_token:
    secure: AAABAPxqz5l9dn9CRjuSdmBw1dz+WQpoqfXJ1pRz5SzsxAuKHMB8mOo+Ir3nCllS0u8VjraFpDnDqGq1SA5a6RbNeOl49eJ+
  ahb-tabellen:imageName: ghcr.io/hochfrequenz/ahb-tabellen
  ahb-tabellen:imageTag: v1.4.0
  ahb-tabellen:makoProzesseBaseUrl: https://mako-prozesse.hochfrequenz.de
  ahb-tabellen:dolmetscherBaseUrl: https://dolmetscher.hochfrequenz.de
  ahb-tabellen:mcpAuth0Audience: https://ahb-tabellen.hochfrequenz.de/mcp
  ahb-tabellen:mcpAuth0IssuerBaseUrl: https://auth.hochfrequenz.de/
  ahb-tabellen:ohDearHealthCheckSecret:
    secure: AAABANrflh/RuuKGiZEPld6MZksWHZZsRfivLLSXEW7gMaC0k+omHcGtixSle5ok
  ahb-tabellen:websitesContainerStartTimeLimit: "300"
  azure-native:clientId: bb60c465-2cfb-4293-9512-e95cd64e59c4
  azure-native:clientSecret:
    secure: AAABABLY112KOyJNBXx5GU8ntV39odLeAdfOqJSkYzoVoJz4pkbShdqj0tVtg2x3QbJ1YSNBxGRIROD5A2vW2pUCf+A5sbAS
  azure-native:location: westeurope
  azure-native:subscriptionId: 2384dcc1-2c97-4c32-932d-44215b137f7a
  azure-native:tenantId: fb2b0361-fa12-48a5-bade-533bf89760d9
  pulumi:template: container-azure-python
