/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DirectionValues } from '../../models/direction-values';

export interface GetDirectionValues$Params {
}

export function getDirectionValues(http: HttpClient, rootUrl: string, params?: GetDirectionValues$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectionValues>> {
  const rb = new RequestBuilder(rootUrl, getDirectionValues.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DirectionValues>;
    })
  );
}

getDirectionValues.PATH = '/api/direction-values';
