/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RichtungValues } from '../../models/richtung-values';

export interface GetRichtungValues$Params {
}

export function getRichtungValues(http: HttpClient, rootUrl: string, params?: GetRichtungValues$Params, context?: HttpContext): Observable<StrictHttpResponse<RichtungValues>> {
  const rb = new RequestBuilder(rootUrl, getRichtungValues.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RichtungValues>;
    })
  );
}

getRichtungValues.PATH = '/api/richtung-values';
