/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Ahb } from '../models/ahb';
import { AhbDiff } from '../models/ahb-diff';
import { AhbDiffSummary } from '../models/ahb-diff-summary';
import { getAhb$Csv } from '../fn/ahb/get-ahb-csv';
import { GetAhb$Csv$Params } from '../fn/ahb/get-ahb-csv';
import { getAhb$Json } from '../fn/ahb/get-ahb-json';
import { GetAhb$Json$Params } from '../fn/ahb/get-ahb-json';
import { getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet } from '../fn/ahb/get-ahb-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params } from '../fn/ahb/get-ahb-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { getAhbDiff } from '../fn/ahb/get-ahb-diff';
import { GetAhbDiff$Params } from '../fn/ahb/get-ahb-diff';
import { getAhbDiffSummary } from '../fn/ahb/get-ahb-diff-summary';
import { GetAhbDiffSummary$Params } from '../fn/ahb/get-ahb-diff-summary';


/**
 * Everything about AHB documents
 */
@Injectable({ providedIn: 'root' })
export class AhbService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAhb()` */
  static readonly GetAhbPath = '/api/ahb/{format-version}/{pruefi}';

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Json$Response(params: GetAhb$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Ahb>> {
    return getAhb$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Json(params: GetAhb$Json$Params, context?: HttpContext): Observable<Ahb> {
    return this.getAhb$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Ahb>): Ahb => r.body)
    );
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params: GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(params: GetAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Observable<Blob> {
    return this.getAhb$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhb$Csv()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Csv$Response(params: GetAhb$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getAhb$Csv(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an AHB document for a Pruefidentifikator from the provided Formatversion.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhb$Csv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhb$Csv(params: GetAhb$Csv$Params, context?: HttpContext): Observable<Blob> {
    return this.getAhb$Csv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getAhbDiffSummary()` */
  static readonly GetAhbDiffSummaryPath = '/api/ahb-diff-summary';

  /**
   * Get aggregated diff statistics for all Pruefidentifikators between two format versions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhbDiffSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhbDiffSummary$Response(params: GetAhbDiffSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<AhbDiffSummary>> {
    return getAhbDiffSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Get aggregated diff statistics for all Pruefidentifikators between two format versions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhbDiffSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhbDiffSummary(params: GetAhbDiffSummary$Params, context?: HttpContext): Observable<AhbDiffSummary> {
    return this.getAhbDiffSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<AhbDiffSummary>): AhbDiffSummary => r.body)
    );
  }

  /** Path part for operation `getAhbDiff()` */
  static readonly GetAhbDiffPath = '/api/ahb-diff/{pruefi}';

  /**
   * Get a diff comparison between two format versions of the same Pruefidentifikator.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAhbDiff()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhbDiff$Response(params: GetAhbDiff$Params, context?: HttpContext): Observable<StrictHttpResponse<AhbDiff>> {
    return getAhbDiff(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a diff comparison between two format versions of the same Pruefidentifikator.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAhbDiff$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAhbDiff(params: GetAhbDiff$Params, context?: HttpContext): Observable<AhbDiff> {
    return this.getAhbDiff$Response(params, context).pipe(
      map((r: StrictHttpResponse<AhbDiff>): AhbDiff => r.body)
    );
  }

}
