/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getFormatVersions } from '../fn/format-versions/get-format-versions';
import { GetFormatVersions$Params } from '../fn/format-versions/get-format-versions';


/**
 * EDIFACT format versions e.g. `FV2510`
 */
@Injectable({ providedIn: 'root' })
export class FormatVersionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFormatVersions()` */
  static readonly GetFormatVersionsPath = '/api/format-versions';

  /**
   * Get a list of all available format versions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFormatVersions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFormatVersions$Response(params?: GetFormatVersions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return getFormatVersions(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of all available format versions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFormatVersions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFormatVersions(params?: GetFormatVersions$Params, context?: HttpContext): Observable<Array<string>> {
    return this.getFormatVersions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
