/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Datenstand } from '../models/datenstand';
import { getDatenstand } from '../fn/maintenance/get-datenstand';
import { GetDatenstand$Params } from '../fn/maintenance/get-datenstand';
import { getHealth } from '../fn/maintenance/get-health';
import { GetHealth$Params } from '../fn/maintenance/get-health';
import { getVersion } from '../fn/maintenance/get-version';
import { GetVersion$Params } from '../fn/maintenance/get-version';
import { HealthCheckResponse } from '../models/health-check-response';
import { Version } from '../models/version';


/**
 * Endpoints which have mainly a technical focus
 */
@Injectable({ providedIn: 'root' })
export class MaintenanceService extends BaseService {
  constructor() {
    const config = inject(ApiConfiguration);
    const http = inject(HttpClient);

    super(config, http);
  }

  /** Path part for operation `getVersion()` */
  static readonly GetVersionPath = '/version';

  /**
   * Get the current version of the AHB-Tabellen application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVersion()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVersion$Response(params?: GetVersion$Params, context?: HttpContext): Observable<StrictHttpResponse<Version>> {
    return getVersion(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the current version of the AHB-Tabellen application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVersion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVersion(params?: GetVersion$Params, context?: HttpContext): Observable<Version> {
    return this.getVersion$Response(params, context).pipe(
      map((r: StrictHttpResponse<Version>): Version => r.body)
    );
  }

  /** Path part for operation `getDatenstand()` */
  static readonly GetDatenstandPath = '/api/datenstand';

  /**
   * Get the latest publication date of the AHB data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDatenstand()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDatenstand$Response(params?: GetDatenstand$Params, context?: HttpContext): Observable<StrictHttpResponse<Datenstand>> {
    return getDatenstand(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the latest publication date of the AHB data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDatenstand$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDatenstand(params?: GetDatenstand$Params, context?: HttpContext): Observable<Datenstand> {
    return this.getDatenstand$Response(params, context).pipe(
      map((r: StrictHttpResponse<Datenstand>): Datenstand => r.body)
    );
  }

  /** Path part for operation `getHealth()` */
  static readonly GetHealthPath = '/api/health';

  /**
   * Health check of the application and its SQLite database.
   *
   * Health check endpoint consumed by [Oh Dear](https://ohdear.app/). The `oh-dear-health-check-secret` request header must match the server's configured secret. Returns HTTP 200 when all checks pass and HTTP 500 when at least one check failed or crashed.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHealth$Response(params: GetHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthCheckResponse>> {
    return getHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * Health check of the application and its SQLite database.
   *
   * Health check endpoint consumed by [Oh Dear](https://ohdear.app/). The `oh-dear-health-check-secret` request header must match the server's configured secret. Returns HTTP 200 when all checks pass and HTTP 500 when at least one check failed or crashed.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHealth(params: GetHealth$Params, context?: HttpContext): Observable<HealthCheckResponse> {
    return this.getHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<HealthCheckResponse>): HealthCheckResponse => r.body)
    );
  }

}
