/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getPruefis } from '../fn/prufidentifikatoren/get-pruefis';
import { GetPruefis$Params } from '../fn/prufidentifikatoren/get-pruefis';


/**
 * Prüfidentifikatoren which is defined by edi@energy, e.g. 55001
 */
@Injectable({ providedIn: 'root' })
export class PrufidentifikatorenService extends BaseService {
  constructor() {
    const config = inject(ApiConfiguration);
    const http = inject(HttpClient);

    super(config, http);
  }

  /** Path part for operation `getPruefis()` */
  static readonly GetPruefisPath = '/api/pruefidentifikatoren/{format-version}';

  /**
   * Get a list of all available Pruefidentifikators for a given format version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPruefis()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPruefis$Response(params: GetPruefis$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'pruefidentifikator'?: string;
'name'?: string;

/**
 * Distinct sender/empfaenger role codes that appear anywhere in this Pruefidentifikator's AHB lines
 */
'roles'?: Array<string>;
}>>> {
    return getPruefis(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of all available Pruefidentifikators for a given format version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPruefis$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPruefis(params: GetPruefis$Params, context?: HttpContext): Observable<Array<{
'pruefidentifikator'?: string;
'name'?: string;

/**
 * Distinct sender/empfaenger role codes that appear anywhere in this Pruefidentifikator's AHB lines
 */
'roles'?: Array<string>;
}>> {
    return this.getPruefis$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<{
'pruefidentifikator'?: string;
'name'?: string;

/**
 * Distinct sender/empfaenger role codes that appear anywhere in this Pruefidentifikator's AHB lines
 */
'roles'?: Array<string>;
}>>): Array<{
'pruefidentifikator'?: string;
'name'?: string;

/**
 * Distinct sender/empfaenger role codes that appear anywhere in this Pruefidentifikator's AHB lines
 */
'roles'?: Array<string>;
}> => r.body)
    );
  }

}
