name: "Pull Request"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.13"
          cache: "npm"

      - name: Install modules
        run: npm ci

      - name: Lint frontend
        run: npm run ng:lint

      - name: Prettier
        run: npm run format:check
